name: Analyse Snyk

on:
  push:
  pull_request:

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Mettre à jour pip, setuptools et wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Installer dépendances Python
        run: pip install -r requirements.txt

      - name: Installer Snyk CLI
        run: npm install -g snyk

      - name: Exécuter l'analyse Snyk
        run: snyk code test --severity-threshold=low --exclude=venv
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
